application/models.py
from werkzeug.security import generate_password_hash, check_password_hash
# from flask_login import UserMixin
from application import db, login_manager
from flask_login import UserMixin


class User(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"


# class HealthFacility(db.Model):
#     __tablename__ = 'health_facilites'
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(64), unique=True, nullable=False)
#     facility_type = db.Column(db.String(20), nullable=False)
#     location = db.Column(db.String(120))
#     email = db.Column(db.String(120))


# class membership(db.Model):
#     __tablename__ = 'members'
#     id = db.Column(db.Integer, primary_key=True)
#     member_name = db.Column(db.String(120), nullable=False)
#     benefciary_name = db.Column(db.String(20), nullable=False)
#     location = db.Column(db.String(120))
#     email = db.Column(db.String(120))


# class expense(db.Model):
#     __tablename__ = 'health_facilites'
#     internal_id = db.Column(db.Integer, primary_key=True)
#     member = db.Column(db.String(64), unique=True, nullable=False)
#     facility_type = db.Column(db.String(20), nullable=False)
#     location = db.Column(db.String(120))
#     email = db.Column(db.String(120))


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

application/__init__.py
from flask import Flask
from config import config
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


login_manager = LoginManager()
db = SQLAlchemy()
login_manager.login_view = "auth.login"


def create_app(config_name):
    app = Flask(__name__)

    # import config parameters to flask app
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    # initilize extensions
    db.init_app(app)
    login_manager.init_app(app)

    # import blueprints and register
    from application.auth.routes import auth
    app.register_blueprint(auth)
    from application.dashboard.routes import dashboard
    app.register_blueprint(dashboard)
    from application.errors.handlers import errors
    app.register_blueprint(errors)
    from application.main.routes import main
    app.register_blueprint(main)

    return app

application/dashboard/routes.py
from flask import Blueprint, render_template, url_for

dashboard = Blueprint('dashboard', __name__)


@dashboard.route('/dashboard')
def plot():
    return render_template('dashboard.html', title='dashboard')

application/main/routes.py
from flask import Blueprint, render_template, url_for

main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('index.html', title='main')

application/templates/dashboard.html
{% extends "layout.html" %}
<!-- prettier-ignore -->
{% block content %}

<div>
    <h1>Dashboard</h1>
    <p>
        The following graphs are interactive
    </p>
    <div class="row">
        <div class="col-md-12 col-lg-6 mt-4">
            <div id="chart"></div>
        </div>
        <div class="col-md-12 col-lg-6 mt-4">
            <div id="chart1"></div>
        </div>
        <div class="col-md-12 col-lg-6 mt-4">
            <div id="chart2"></div>
        </div>
    </div>
</div>



<script type="text/javascript" src="{{ url_for('static', filename='js/graph.js') }}"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>
<!-- prettier-ignore -->
{% endblock content %}

application/templates/index.html
{% extends "layout.html" %}
<!-- prettier-ignore -->
{% block content %}

<div>
    <h1>Hello there</h1>
    <p>
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Magni
        voluptate repudiandae culpa, impedit ea iusto quaerat veniam commodi
        delectus accusamus soluta debitis illo sed dicta, natus excepturi
        accusantium nemo itaque!
    </p>
</div>

<!-- prettier-ignore -->
{% endblock content %}

application/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <!-- prettier-ignore -->
    {% if title %}
    <title>Dalil Shafi - {{ title }}</title>
    <!-- prettier-ignore -->
    {% else %}
    <title>Dalil Shafi</title>
    <!-- prettier-ignore -->
    {% endif %}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="../static/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}" />

    <!-- JQuery -->
    <script src="../static/js/jquery-3.3.1.min.js"></script>
    <!-- Bootstrap JS -->
    <script src="../static/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <!-- navigation bar -->
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">Dalil Shafi</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/">Home</a>
                        <a class="nav-item nav-link" href="{{ url_for('dashboard.plot') }}">Dashboard</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        <a class="nav-item nav-link" href="{{ url_for('auth.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                        <a class="nav-item nav-link" href="{{ url_for('auth.register') }}">Register</a>
                        <a class="nav-item nav-link" href="/email">email</a>
                    </div>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="container">
        <!-- prettier-ignore -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        <!-- prettier-ignore -->
        {% if messages %}
        <!-- prettier-ignore -->
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">{{ message }}</div>
        <!-- prettier-ignore -->
        {% endfor%}
        <!-- prettier-ignore -->
        {% endif %}
        <!-- prettier-ignore -->
        {% endwith %}
        <!-- prettier-ignore -->
        {% block content %}{% endblock %}
    </main>

    <!-- footer -->
    <footer class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel">
            <div class="container">
                <a class="navbar-brand mr-4" href="/">contact us</a>
            </div>
        </nav>
    </footer>


</body>

</html>

application/templates/login.html
{% extends "layout.html" %}
<!-- prettier-ignore -->
{% block title %}Dalilshafi - Login{% endblock %}
<!-- prettier-ignore -->
{% block content %}

<div class="content-section">
    <form method="POST" action="">
        <!-- prettier-ignore -->
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-buttom mb-4">Sign in</legend>
            <div class="form-group">
                <!-- prettier-ignore -->
                {{ form.username.label(class="form-control-label") }}
                <!-- prettier-ignore -->
                {% if form.username.errors %}
                <!-- prettier-ignore -->
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                <!-- prettier-ignore -->
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                <!-- prettier-ignore -->
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- prettier-ignore -->
                {% if form.password.errors %}
                <!-- prettier-ignore -->
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }}
                <!-- prettier-ignore -->
                {% endif %}
            </div>
            <div class="form-check">
                {{ form.remember_me(class="form-check-input") }}
                {{ form.remember_me.label(class="form-check-label") }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Don't have an account?
        <a class="ml-2" href="{{ url_for('auth.register') }}">Register</a>
    </small>
</div>
<!-- prettier-ignore -->
{% endblock content %}

application/templates/register.html
{% extends "layout.html" %}
<!-- prettier-ignore -->
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        <!-- prettier-ignore -->
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            <div class="form-group">
                <!-- prettier-ignore -->
                {{ form.username.label(class="form-control-label") }}
                <!-- prettier-ignore -->
                {% if form.username.errors %}
                <!-- prettier-ignore -->
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                <!-- prettier-ignore -->
                {% else %}
                {{ form.username(class="form-control form-control-lg") }}
                <!-- prettier-ignore -->
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                <!-- prettier-ignore -->
                {% if form.email.errors %}
                <!-- prettier-ignore -->
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %}
                <!-- prettier-ignore -->
                {{ form.email(class="form-control form-control-lg") }} {% endif
                %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                <!-- prettier-ignore -->
                {% if form.password.errors %}
                <!-- prettier-ignore -->
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %}
                {{ form.password(class="form-control form-control-lg") }} {%
                endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }} {%
                if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span> {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Already Have An Account?
        <a class="ml-2" href="{{ url_for('auth.login') }}">Sign In</a>
    </small>
</div>
{% endblock content %}